JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps/JWBasicVideoViewController.h, JWBestPracticeApps/JWBestPracticeApps/JWBasicVideoViewController.m, JWBestPracticeApps/JWCasting/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/JWFriendlyObstructions/AppDelegate.h, JWBestPracticeApps/JWFriendlyObstructions/AppDelegate.m, JWBestPracticeApps/JWFriendlyObstructions/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/JWFriendlyObstructions/Assets.xcassets/Contents.json, JWBestPracticeApps/JWFriendlyObstructions/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWFriendlyObstructions/Base.lproj/Main.storyboard, JWBestPracticeApps/JWFriendlyObstructions/Info.plist, JWBestPracticeApps/JWFriendlyObstructions/JWFriendlyObstructionViewController.h, JWBestPracticeApps/JWFriendlyObstructions/JWFriendlyObstructionViewController.m, JWBestPracticeApps/JWFriendlyObstructions/main.m, JWBestPracticeApps/Podfile, JWBestPracticeApps/Podfile.lock, JWBestPracticeApps/Voicer/Assets.xcassets/AppIcon.appiconset/Contents.json
- Creates a demo project using the Experimental API to register friendly obstructions.
- Sets up a chromeless player and adds a custom UI button on it
- the player plays a google IMA preRoll
- listens for JWPlayerDelegate calls to update the button
- upgrades to latest Chromecast dependency
=> Friendly obstructions

JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWAirPlay.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWBestPracticeApps.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWCasting.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWSiriVideoExtension.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWVoiceControl.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/Voicer.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/VoicerExtension.xcscheme, JWBestPracticeApps/JWBestPracticeApps/JWBasicVideoViewController.m, JWBestPracticeApps/JWConviva/AnalyticsObserver.swift, JWBestPracticeApps/JWConviva/JWConviva-Bridging-Header.h, JWBestPracticeApps/JWFairPlayDrm/AppDelegate.swift, JWBestPracticeApps/JWFairPlayDrm/JWFairPlayDrmViewController.swift, JWBestPracticeApps/JWRemotePlayer/JWRemotePlayerViewController.h, JWBestPracticeApps/Podfile, JWBestPracticeApps/Podfile.lock, JWBestPracticeApps/Voicer/AppDelegate.swift, JWBestPracticeApps/Voicer/VoicerViewController.swift, JWBestPracticeApps/VoicerExtension/IntentHandler.swift
Workspace update
- Update targets from Swift 3 to Swift 5
- Update outdated libraries (JWPlayerSDK and Google IMA)
Get the repository updated to latest versions and standards.
The PR #21 should be merged after this PR.
Addresses Issue(s):
[SDK-4639],[SDK-4525],[SDK-4526],[SDK-4527]
[SDK-4639]: https://jwplayer.atlassian.net/browse/SDK-4639
[SDK-4525]: https://jwplayer.atlassian.net/browse/SDK-4525
[SDK-4526]: https://jwplayer.atlassian.net/browse/SDK-4526
[SDK-4527]: https://jwplayer.atlassian.net/browse/SDK-4527
=> [SDK-4639][SDK-4525][SDK-4526][SDK-4527] Workspace update

JWBestPracticeApps/FeedTableViewController/FeedTableViewController.swift
The FeedTableViewController project in JWBestPractices was not compiling. These changes fix this issues in the code.
=> [SDK-4656] fixes build errors in FeedTableViewController

JWBestPracticeApps/Casting/AppDelegate.swift, JWBestPracticeApps/Casting/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Casting/Assets.xcassets/Contents.json, JWBestPracticeApps/Casting/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Casting/Base.lproj/Main.storyboard, JWBestPracticeApps/Casting/Casting.entitlements, JWBestPracticeApps/Casting/CastingViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/Casting.xcscheme, JWBestPracticeApps/Podfile
Added CastingViewController using Swfit 5 to have a mirror example of JWCastingViewController(Obj-C)
Show an example of how to use the cast feature using the JWCastController.
To have a Swift version of JWCastingViewController
This PR should be merged with [SDK-4519]
Addresses Issue(s):
[SDK-4520]
[SDK-4519]: https://jwplayer.atlassian.net/browse/SDK-4519
[SDK-4520]: https://jwplayer.atlassian.net/browse/SDK-4520
=> [SDK-4520] Added casting example using Swfit 5 

JWBestPracticeApps/JWFriendlyObstructions/JWFriendlyObstructionViewController.m
Updated the friendly obstructions best practices app to include the new Friendly Obstructions API.
=> [SDK-4756] Updated the friendly obstructions best practices app.

JWBestPracticeApps/AirPlay/AppDelegate.swift, JWBestPracticeApps/AirPlay/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/AirPlay/Assets.xcassets/Contents.json, JWBestPracticeApps/AirPlay/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/AirPlay/Base.lproj/Main.storyboard, JWBestPracticeApps/AirPlay/README.md, JWBestPracticeApps/AirPlay/ViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/Podfile, README.md
Adds an example to illustrate how to support AirPlay.
Addresses Issue(s):
SDK-4521
=> [SDK-4521] Added AirPlay target using Swift 5 to have a mirror example of JWAirPlay(Obj-C)

JWBestPracticeApps/JWAirPlay/README.md
noted that this best practice app is in objective c in the readme
=> Added Obj-c to readme

JWBestPracticeApps/FeedTableViewController/README.md, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj
Adds README for the FeedTableViewController target.
=> [SDK-4654] Adds README for the FeedTableViewController target

README.md
Updates the repo's README:
* Brief description of the latest added best practice apps.
* Latest version compatible with Google Cast SDK.
=> [SDK-4635] Updates the repo's README

JWBestPracticeApps/Podfile
Updates podfile with the latest JWPlayer SDK & Google Cast SDK versions.
=> Updates podfile

JWBestPracticeApps/GoogleDAI/AppDelegate.swift, JWBestPracticeApps/GoogleDAI/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/GoogleDAI/Assets.xcassets/Contents.json, JWBestPracticeApps/GoogleDAI/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/GoogleDAI/Base.lproj/Main.storyboard, JWBestPracticeApps/GoogleDAI/GoogleDAI-Bridging-Header.h, JWBestPracticeApps/GoogleDAI/Info.plist, JWBestPracticeApps/GoogleDAI/SceneDelegate.swift, JWBestPracticeApps/GoogleDAI/ViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/Podfile
This PR creates a new target "GoogleDAI" which uses a live stream as an example. The live stream used is the stream from Google's sample page: https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/testing-dai
I had to up the Podfile to iOS 3.12.0
=> [SDK-5496] Created a GoogleDAI target with a live stream sample.

JWBestPracticeApps/GoogleDAI/Base.lproj/Main.storyboard, JWBestPracticeApps/GoogleDAI/GoogleDAIViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/Podfile, README.md
This PR introduces some minor adjustments for the GoogleDAI target:
- Renames the ViewController to GoogleDAIViewController, inheriting from BaseViewController, restricting the amount of code presented to the bare minimum needed to add DAI functionality to your app.
- Bumps the IMA version to 3.11.3
- Adds a note in the readme
=> Google DAI adjustments

JWBestPracticeApps/Casting-GCKUICastButton/AppDelegate.swift, JWBestPracticeApps/Casting-GCKUICastButton/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Casting-GCKUICastButton/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Casting-GCKUICastButton/Assets.xcassets/Contents.json, JWBestPracticeApps/Casting-GCKUICastButton/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Casting-GCKUICastButton/Base.lproj/Main.storyboard, JWBestPracticeApps/Casting-GCKUICastButton/CastingGCKViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/Casting.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWAirPlay.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWBestPracticeApps.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/JWCasting.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/NativeControls.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/Voicer.xcscheme, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/xcshareddata/xcschemes/VoicerExtension.xcscheme, JWBestPracticeApps/JWBestPracticeApps/Info.plist, JWBestPracticeApps/JWBestPracticeApps/JWBasicVideoViewController.m, JWBestPracticeApps/JWCasting-GCKUICastButton/AppDelegate.h, JWBestPracticeApps/JWCasting-GCKUICastButton/AppDelegate.m, JWBestPracticeApps/JWCasting-GCKUICastButton/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/JWCasting-GCKUICastButton/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/JWCasting-GCKUICastButton/Assets.xcassets/Contents.json, JWBestPracticeApps/JWCasting-GCKUICastButton/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWCasting-GCKUICastButton/Base.lproj/Main.storyboard, JWBestPracticeApps/JWCasting-GCKUICastButton/JWCastingGCKViewController.h, JWBestPracticeApps/JWCasting-GCKUICastButton/JWCastingGCKViewController.m, JWBestPracticeApps/JWCasting-GCKUICastButton/main.m, JWBestPracticeApps/Podfile
Creates app targets to demonstrate how to use the GCKUICastButton with our SDK.
=> [SDK-7883] Create best practices apps for GCKUICastButton

JWBestPracticeApps/Google IMA Ads/Google IMA Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/AppDelegate.swift, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Assets.xcassets/Contents.json, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Base.lproj/Main.storyboard, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/Info.plist, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/SceneDelegate.swift, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/ViewController.swift, JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Podfile
Adds the new Google IMA Ads project for demoing how to set up a player with Google IMA.
=> [SDK-8189] Adds Google IMA Ads BPA

JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Podfile, JWBestPracticeApps/Recommendations/Recommendations.xcodeproj/project.pbxproj, JWBestPracticeApps/Recommendations/Recommendations/AppDelegate.swift, JWBestPracticeApps/Recommendations/Recommendations/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Recommendations/Recommendations/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Recommendations/Recommendations/Assets.xcassets/Contents.json, JWBestPracticeApps/Recommendations/Recommendations/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Recommendations/Recommendations/Base.lproj/Main.storyboard, JWBestPracticeApps/Recommendations/Recommendations/Info.plist, JWBestPracticeApps/Recommendations/Recommendations/SceneDelegate.swift, JWBestPracticeApps/Recommendations/Recommendations/ViewController.swift, README.md
Created a Best Practice App demonstrating the related content functionality with our 4.0 SDK.
=> [SDK-8194] Created Recommendations Best Practice App

JWBestPracticeApps/Google DAI Ads/Google DAI Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/AppDelegate.swift, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Assets.xcassets/Contents.json, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Base.lproj/Main.storyboard, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/Info.plist, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/SceneDelegate.swift, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/ViewController.swift, JWBestPracticeApps/Google DAI Ads/README.md, JWBestPracticeApps/Google IMA Ads/Google IMA Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Google IMA Ads/README.md, JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/JWPlayer Ads/JWPlayer Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Podfile, README.md
=> [SDK-8190] Adds the Google DAI Ads BPA

JWBestPracticeApps/ChromeCast/ChromeCast.xcodeproj/project.pbxproj, JWBestPracticeApps/ChromeCast/ChromeCast/AppDelegate.swift, JWBestPracticeApps/ChromeCast/ChromeCast/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/ChromeCast/ChromeCast/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/ChromeCast/ChromeCast/Assets.xcassets/Contents.json, JWBestPracticeApps/ChromeCast/ChromeCast/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/ChromeCast/ChromeCast/Base.lproj/Main.storyboard, JWBestPracticeApps/ChromeCast/ChromeCast/Info.plist, JWBestPracticeApps/ChromeCast/ChromeCast/SceneDelegate.swift, JWBestPracticeApps/ChromeCast/ChromeCast/ViewController.swift, JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Podfile, README.md
Created a Best Practice App for ChromeCast. This demonstrates how to setup an app for ChromeCast.
=> [SDK-8192] Created ChromeCast best practice app

JWBestPracticeApps/ChromeCast/ChromeCast.xcodeproj/project.pbxproj, JWBestPracticeApps/Recommendations/Recommendations.xcodeproj/project.pbxproj
Lowers deployment to 14.4 to allow build machine to build this.
=> Lower deployment for build machine

JWBestPracticeApps/DRM Fairplay/DRM Fairplay/ViewController.swift
=> [SDK-8193] Added fix for playing EZDRM stream

JWBestPracticeApps/Podfile
Updated Podfile with the latest JWPlayerSDK v3.21.x & GoogleIMASDK 3.14.3.
=> Updated Podfile

JWBestPracticeApps/JWAirPlay/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWBestPracticeApps/Base.lproj/Main.storyboard, JWBestPracticeApps/JWCasting/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWFairPlayDrm/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWFairPlayDrm/Base.lproj/Main.storyboard, JWBestPracticeApps/JWRemoteCastController/Base.lproj/Interface.storyboard, JWBestPracticeApps/JWRemoteCastPlayer/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/JWRemoteCastPlayer/Base.lproj/Main.storyboard, JWBestPracticeApps/JWRemoteController/Base.lproj/Interface.storyboard, JWBestPracticeApps/JWRemotePlayer/Base.lproj/LaunchScreen.storyboard
Update Storyboard and LaunchScreen toolsVersion and plugIn versions for Xcode 13+ - Applicable to v3 only
Update out of date document toolsVersion to fix beachballing Xcode 13+
Update out of date dependencies plugIn to fix beachballing Xcode 13+
Remove unused <animations> tag
=> Bugfix/update outdated IB versions

JWBestPracticeApps/BasicPlayer/BasicPlayer.xcodeproj/project.pbxproj, JWBestPracticeApps/Google DAI Ads/Google DAI Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Google IMA Ads/Google IMA Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/JWPlayer Ads/JWPlayer Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Podfile
Removed the GoogleCast library from project not demonstrating casting.
=> [SDK-8496] Removed GoogleCast from projects not demonstrating it.

JWBestPracticeApps/Recommendations/Recommendations/ViewController.swift
Adds a boolean to switch between global and player item recommendations
=> Adds a boolean to switch between global and player item recommendations

JWBestPracticeApps/BasicPlayer/BasicPlayer-Swift/Info.plist
Basic Player info.plist was renamed, this brings it back
=> Return info.plist to basic player

JWBestPracticeApps/Custom UI/Custom UI.xcodeproj/project.pbxproj, JWBestPracticeApps/Custom UI/Custom UI/Custom Player/xibs/AdControls.xib, JWBestPracticeApps/Custom UI/Custom UI/Custom Player/xibs/VideoControls.xib, JWBestPracticeApps/Custom UI/Custom UI/Info.plist
Fixed issue in Custom UI BPA where buttons were not readable in dark mode.
=> [SDK-9229] Fixed dark mode on Custom UI BPA

JWBestPracticeApps/FeedCollectionViewController/FeedItemCell.swift, JWBestPracticeApps/FeedTableViewController/FeedItemCell.swift, JWBestPracticeApps/FeedTableViewController/FeedItemCell.xib, JWBestPracticeApps/FeedTableViewController/FeedTableViewController.swift, JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj
Fixed crashes in FeedVideoController and AutoplayVideoFeed related to nib files being unable to find the proper IBOutlets.
=> [SDK-9429] Fixed crashes in FeedVideoController and AutoplayVideoFeed

JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Picture in Picture/Picture in Picture.xcodeproj/project.pbxproj, JWBestPracticeApps/Picture in Picture/Picture in Picture/AppDelegate.swift, JWBestPracticeApps/Picture in Picture/Picture in Picture/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Picture in Picture/Picture in Picture/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Picture in Picture/Picture in Picture/Assets.xcassets/Contents.json, JWBestPracticeApps/Picture in Picture/Picture in Picture/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Picture in Picture/Picture in Picture/Base.lproj/Main.storyboard, JWBestPracticeApps/Picture in Picture/Picture in Picture/Info.plist, JWBestPracticeApps/Picture in Picture/Picture in Picture/PlayerViewController.swift, JWBestPracticeApps/Picture in Picture/Picture in Picture/SceneDelegate.swift, JWBestPracticeApps/Picture in Picture/Picture in Picture/ViewController.swift, JWBestPracticeApps/Picture in Picture/README.md, JWBestPracticeApps/Podfile, README.md
This BPA includes:
* README.md file
* PiP project
* Audio, AirPlay, and Picture in Picture background mode enabled
* How to activate the AVAudioSession
* How to interact with the JWPlayerViewController to toggle PiP functionality
* How to listen for PiP events
* Podfile updated
=> [SDK-8851] Picture in Picture BPA

JWBestPracticeApps/Captions/Captions.xcodeproj/project.pbxproj, JWBestPracticeApps/Captions/Captions.xcodeproj/project.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Captions/Captions.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, JWBestPracticeApps/Captions/Captions/AppDelegate.swift, JWBestPracticeApps/Captions/Captions/Assets.xcassets/AccentColor.colorset/Contents.json, JWBestPracticeApps/Captions/Captions/Assets.xcassets/AppIcon.appiconset/Contents.json, JWBestPracticeApps/Captions/Captions/Assets.xcassets/Contents.json, JWBestPracticeApps/Captions/Captions/Base.lproj/LaunchScreen.storyboard, JWBestPracticeApps/Captions/Captions/Base.lproj/Main.storyboard, JWBestPracticeApps/Captions/Captions/Info.plist, JWBestPracticeApps/Captions/Captions/PlayerViewController.swift, JWBestPracticeApps/Captions/Captions/SceneDelegate.swift, JWBestPracticeApps/Captions/Captions/ViewController.swift, JWBestPracticeApps/Captions/README.md, JWBestPracticeApps/JWBestPracticeApps-4x.xcworkspace/contents.xcworkspacedata, JWBestPracticeApps/Podfile, README.md
This Captions best practices app demonstrates the following functionality:
1. Listen for caption events
2. Disable caption rendering
3. Display captions in a different view.
=> [SDK-10327] Captions best practices app

JWBestPracticeApps/DRM Fairplay/DRM Fairplay.xcodeproj/project.pbxproj, JWBestPracticeApps/DRM Fairplay/DRM Fairplay/DRMPlaylist.swift, JWBestPracticeApps/DRM Fairplay/DRM Fairplay/ViewController.swift
This updates the DRM Fairplay demo to use our Studio DRM
We needed to update the current implementation of Fairplay DRM
Playlist implementation was taken from https://docs.jwplayer.com/players/docs/ios-apply-studio-drm-with-jw-platform#implementation 
[SDK-9988]
[SDK-9988]: https://jwplayer.atlassian.net/browse/SDK-9988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SDK-9988] Update DRM BPA to use Studio DRM

JWBestPracticeApps/Podfile
* Sets specific version for the GoogleCast pod.
* Sets NO for the ONLY_ACTIVE_ARCH build setting.
=> Uses currently supported google cast pod

JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/Base.lproj/Main.storyboard, JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/CustomControls.swift, JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/CustomControls.xib, JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/ViewController.swift
Fixed issue where the UI for the AdvancedPlayer BPA was not showing up quickly enough. This was due to UI code being called outside of the main thread.
Fixed the interface of the AdvancedPlayer BPA to look a bit nicer.
Changed the stream to Big Buck Bunny to match the poster image.
The full screen constraints have been fixed so it looks better in full screen mode when switching in and out of full screen.
=> [SDK-10968][SDK-10827] Improved look and performance of AdvancedPlayer BPA

JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/ViewController.swift, JWBestPracticeApps/BasicTVPlayer/BasicTVPlayer.xcodeproj/project.pbxproj, JWBestPracticeApps/Custom UI/Custom UI/Custom Player/PlayerViewController.swift, JWBestPracticeApps/Google DAI Ads/Google DAI Ads/ViewController.swift, JWBestPracticeApps/Google IMA Ads/Google IMA Ads/ViewController.swift, JWBestPracticeApps/Google IMA companion ads/Google IMA Companion Ads.xcodeproj/project.pbxproj, JWBestPracticeApps/Google IMA companion ads/Google IMA Companion Ads/PlayerViewController.swift, JWBestPracticeApps/JWPlayer Ads/JWPlayer Ads/ViewController.swift, JWBestPracticeApps/Offline DRM/Offline DRM.xcodeproj/project.pbxproj, JWBestPracticeApps/Picture in Picture/Picture in Picture.xcodeproj/project.pbxproj, JWBestPracticeApps/Recommendations/Recommendations/ViewController.swift
Updates the Ad Event method signature in BPAs using it, for 4.13.0
=> Updated ad event method signature for 4.13.0

JWBestPracticeApps/Podfile
Update iphone deployment target deployment to be 14 for all targets
=> Update iphone deployment target deployment to be 14 for all targets

JWBestPracticeApps/Offline DRM/Offline DRM/ViewController.swift
The Cell Image Loader now has async methods, preventing the Offline DRM BPA from building.
That BPA would need further optimization to actually leverage Swift Concurrency (first by bridging the Apple APIs that use the delegate pattern).
=> [SDK-11469] Offline DRM: Minimal update for Swift Concurrency migration

JWBestPracticeApps/Podfile
Update to most recent release.
=> Release 4.21.1

JWBestPracticeApps/Podfile
=> upgrade to iOS 4.21.2
