jwplayer/jwplayer-ios-bestPracticeApps

- JWBestPracticeApps/FeedTableViewController/FeedItemCell.swift
- JWBestPracticeApps/FeedTableViewController/FeedTableViewController.swift
Removed scrolling monitoring which caused jitter by calling pause() and filtering the players with every small amount of scrolling.
Moved TableCell UI code into the FeedItemCell, where now it removes the subviews of the container view on prepareForReuse(). It also takes a player as an argument, and adds the view to the container itself.
> [SDK-4821] Refactored FeedTableViewController Demo

- JWBestPracticeApps/JWAirPlay/Base.lproj/Main.storyboard
- JWBestPracticeApps/JWAirPlay/JWAirPlayViewController.m
- JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj
Updates JWAirPlay BestPracticeApp to use the AVRoutePickerView control after iOS 11 and keep using MPVolumeView control for previous iOS versions.
> [SDK-4723] Update JWAirPlay Best Practice App to use AirPlay 2

- JWBestPracticeApps/JWBestPracticeApps/Info.plist
With iOS 13, Apple has introduced stricter permission requirements that impact apps using the Google Cast SDK. The 'NSBluetoothAlwaysUsageDescription' key is necessary on iOS 13 to run the Casting and JWCasting best practice apps without crashing.
> [SDK-4953] Added bluetooth usage description to the info.plist

- JWBestPracticeApps/JWCasting/README.md
* Removed beta reference (was never in beta)
* Updated "known issues" section to reflect similar language used in developer docs: https://developer.jwplayer.com/sdk/ios/docs/developer-guide/casting/chromecast/
> Updated readme

- JWBestPracticeApps/JWBestPracticeApps.xcodeproj/project.pbxproj
- JWBestPracticeApps/JWLockScreenControls/AppDelegate.h
- JWBestPracticeApps/JWLockScreenControls/AppDelegate.m
- JWBestPracticeApps/JWLockScreenControls/Assets.xcassets/AppIcon.appiconset/Contents.json
- JWBestPracticeApps/JWLockScreenControls/Assets.xcassets/Contents.json
- JWBestPracticeApps/JWLockScreenControls/Base.lproj/LaunchScreen.storyboard
- JWBestPracticeApps/JWLockScreenControls/Base.lproj/Main.storyboard
- JWBestPracticeApps/JWLockScreenControls/JWLockScreenViewController.h
- JWBestPracticeApps/JWLockScreenControls/JWLockScreenViewController.m
- JWBestPracticeApps/JWLockScreenControls/main.m
- JWBestPracticeApps/LockScreenControls/AppDelegate.swift
- JWBestPracticeApps/LockScreenControls/Assets.xcassets/AppIcon.appiconset/Contents.json
- JWBestPracticeApps/LockScreenControls/Assets.xcassets/Contents.json
- JWBestPracticeApps/LockScreenControls/Base.lproj/LaunchScreen.storyboard
- JWBestPracticeApps/LockScreenControls/Base.lproj/Main.storyboard
- JWBestPracticeApps/LockScreenControls/LockScreenControls-Bridging-Header.h
- JWBestPracticeApps/LockScreenControls/LockScreenViewController.swift
- JWBestPracticeApps/Podfile
This PR adds an Obj-C and Swift target to showcase how to control which player is controlled by the lock screen through the 'displayLockScreenControls' property.
> [SDK-5976] Best practice apps to showcase how to use 'displayLockScreenControls'

- JWBestPracticeApps/AdvancedPlayer/AdvancedPlayer/ViewController.swift
* Show custom controls when the player is set up successfully.
* Hides custom controls when the player setup fails.
> [SDK-9735] Handle custom controls visibility based on the setup events

- JWBestPracticeApps/Custom UI/Custom UI/Custom Player/PlayerViewController.swift
The purpose of this PR is to resume playback after entering fullscreen mode.
The AVPlayer seems to automatically paused when it's moved in the view hierarchy. We account for this in our UI code by checking the state of the player before it enters fullscreen, and resuming playback after entering fullscreen if it was playing. I implement something similar here.
> [SDK-10499] Resume playback after entering fullscreen mode

- JWBestPracticeApps/BasicPlayer/BasicPlayer.xcodeproj/project.pbxproj
This changes the pod generated .framework to `do not embed` to allow installing and running on device.
> Fix issue for installing BasicPlayer-Swift on device

- JWBestPracticeApps/DRM Fairplay/README.md
This updates the readme for the DRM Fairplay project so that it does not mention EZDRM
It references EZDRM instead of Studio DRM
> Update DRM FairPlay ReadMe

- JWBestPracticeApps/BasicPlayer/BasicPlayer.xcodeproj/project.pbxproj
- JWBestPracticeApps/Offline DRM/Offline DRM/AppDelegate.swift
- JWBestPracticeApps/Offline DRM/Offline DRM/ViewController.swift
This prevents build errors when building from BPA scripts, by not having placeholders directly in code
The BPA build script does not do any code changes to build these, so we fail to build if they are present
> Fix for building with available values.

- JWBestPracticeApps/Custom UI/Custom UI/Custom Player/PlayerViewController.swift
* This uses the same logic when going to fullscreen to resume the previous state that was used when the transition ended.
Playback pauses after returning from fullscreen if the app was previously backgrounded
None
None
[SDK-10499]
iOS-####
`test this please` - re-run the PR builder
`Test {tag) tag, please` - run the tags specified against the JWPlayerKitTestApp
`Test (scenarioLocation) scenario, please` - run the scenario at the scenario location against the JWPlayerKitTestApp
[SDK-10499]: https://jwplayer.atlassian.net/browse/SDK-10499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDK-10499] Resume state after exiting fullscreen

- JWBestPracticeApps/Custom UI/Custom UI/Custom Player/PlayerViewController.swift
- JWBestPracticeApps/Picture in Picture/Picture in Picture/Base.lproj/Main.storyboard
- JWBestPracticeApps/Picture in Picture/Picture in Picture/ViewController.swift
* Since the PiPController is not created if it is not PiP compatible it cannot start listening to PiP availability in the context. If we set to disabled as the default it will only change if PiP is possible.
PiP button appears as enabled on non supported OS
None
None
[SDK-9523]
iOS-####
`test this please` - re-run the PR builder
`Test {tag) tag, please` - run the tags specified against the JWPlayerKitTestApp
`Test (scenarioLocation) scenario, please` - run the scenario at the scenario location against the JWPlayerKitTestApp
[SDK-9523]: https://jwplayer.atlassian.net/browse/SDK-9523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SDK-9523] Set PiP button default to disabled

- JWBestPracticeApps/Offline DRM/Offline DRM/ViewController.swift
Places URL in a guard statement to prevent crashing when someone does not supply a valid URL for the content.
> [SDK-10826] Tweaked code to prevent a crash when DRM demo has invalid URL

- JWBestPracticeApps/Google IMA Ads/Google IMA Ads/AppDelegate.swift
- JWBestPracticeApps/Google IMA companion ads/Google IMA Companion Ads/AppDelegate.swift
IMA ads were not playing audio on physical devices when the hardware audio shutoff button was in the 'off' position. This PR fixes it so this button does not affect the audio playback of the IMA ads.
> [SDK-10858] Fixed audio so it plays for IMA with hardware audio shutoff enabled.

- JWBestPracticeApps/Custom UI/Custom UI/Assets.xcassets/BackgroundColor.colorset/Contents.json
- JWBestPracticeApps/Custom UI/Custom UI/Base.lproj/Main.storyboard
- JWBestPracticeApps/Custom UI/Custom UI/Custom Player/xibs/ErrorView.xib
Improved Custom UI BPA so that it is more visible in Dark Mode. For example, the text color on the error screen was getting set to black, it is now set to white.
Evidence:
https://github.com/jwplayer/jwplayer-ios-bestPracticeApps/assets/54856472/da1c2fc3-02a0-4f9b-821b-99483586a071
> [SDK-10969] Custom UI BPA reacts better to dark mode.

- JWBestPracticeApps/Podfile
pod `'JWPlayerKit', '~> 3.18.4'` will update to 3.18.5, which does not support iOS 12 or 13.
It should be changed to pod `'JWPlayerKit', '3.18.4'` so that version gets installed, no more, no less.
> [SDK-11103] Updates Podfile for precise IMA version

- JWBestPracticeApps/Picture in Picture/Picture in Picture/Base.lproj/Main.storyboard
Without constraints (like in the other BPA projects), the UX was bad, since it was unexpectedly short in landscape mode.
> [SDK-11232] Adds constraints to player view to fill superview

- JWBestPracticeApps/Chromecast-GCKUICastButton/ChromeCast-GCKUICastButton/ViewController.swift
- JWBestPracticeApps/Podfile
* No API changes needed for the update to 4.8.0
* Change in Podfile, though note that this does not work (as described in our docs and the ReadMe) and is only a 'POC' pod addition (as expected).
* Added trivial implementation of the new `GCKUICastButtonDelegate`.
> [SDK-10338] Updates cast SDK to 4.8.0; implements cast button delegate

- JWBestPracticeApps/FeedTableViewController/FeedTableViewController.xcodeproj/project.pbxproj
- JWBestPracticeApps/FeedTableViewController/FeedTableViewController/Feed/Playlist.swift
As a 'Tik Tok-esque' scrolling feed, no need for landscape mode, and so it does not account for it (constraints or otherwise).
> Locks the app to `.portrait` orientation

- JWBestPracticeApps/Podfile
Default min SDK version set to 4.19.0 b/c [Privacy Manifest](https://releases.jwplayer.com/label/43616#:~:text=JWP%20iOS%20SDK%20contains%20a%20privacy%20manifest%20file%20(PrivacyInfo.xcprivacy)%20and%20a%20signature%20for%20the%20SDK.)
[Same reason](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/history?hl=en#:~:text=Adds%20a%20privacy%20manifest%20PrivacyInfo.xcprivacy%20file%20and%20a%20signature%20for%20the%20SDK.) for requiring IMA 3.22.0
> [SDK-11385] Updates Podfile versions for 4.19.0

- JWBestPracticeApps/Google DAI Ads/Google DAI Ads/ViewController.swift
Tears of Steel, the [DAI sample stream](https://developers.google.com/ad-manager/dynamic-ad-insertion/streams#vod_stream_samples) has a new CMS ID number, needed for the BPA to work.
Old: `2528370`
New: `2548831`
> [SDK-11575] Update the DAI BPA with new default CMS ID
